// Autogenerated, edition is futile
package com.heeere.omiscidgui.eaa.adapterframework.model;

public class ProvidedSlot {

    protected java.beans.PropertyChangeSupport ___pcs = new java.beans.PropertyChangeSupport(this);
    public void addPropertyChangeListener(java.beans.PropertyChangeListener l) {___pcs.addPropertyChangeListener(l);}
    public void removePropertyChangeListener(java.beans.PropertyChangeListener l) {___pcs.removePropertyChangeListener(l);}
    public ProvidedSlot(ServiceSpecification specification, Adapter possibleParentAdapter, fr.prima.omiscid.user.service.ServiceProxy possibleServiceProxy) {
        this.specification = specification;
        this.possibleParentAdapter = possibleParentAdapter;
        this.possibleServiceProxy = possibleServiceProxy;
    }

    private ServiceSpecification specification;
    public ServiceSpecification getSpecification() {
        return specification;
    }
    public void setSpecification(ServiceSpecification specification) {
        ServiceSpecification __old = this.specification;
        this.specification = specification;
        ___pcs.firePropertyChange("specification", __old, this.specification);
    }

    private Adapter possibleParentAdapter;
    public Adapter getPossibleParentAdapter() {
        return possibleParentAdapter;
    }
    public void setPossibleParentAdapter(Adapter possibleParentAdapter) {
        Adapter __old = this.possibleParentAdapter;
        this.possibleParentAdapter = possibleParentAdapter;
        ___pcs.firePropertyChange("possibleParentAdapter", __old, this.possibleParentAdapter);
    }

    private fr.prima.omiscid.user.service.ServiceProxy possibleServiceProxy;
    public fr.prima.omiscid.user.service.ServiceProxy getPossibleServiceProxy() {
        return possibleServiceProxy;
    }
    public void setPossibleServiceProxy(fr.prima.omiscid.user.service.ServiceProxy possibleServiceProxy) {
        fr.prima.omiscid.user.service.ServiceProxy __old = this.possibleServiceProxy;
        this.possibleServiceProxy = possibleServiceProxy;
        ___pcs.firePropertyChange("possibleServiceProxy", __old, this.possibleServiceProxy);
    }

    public String deepToString(String indent, String delta, int maxDepth) {
        if (maxDepth <= 0) { return "!!!MAX!!!\n";}
        StringBuilder res = new StringBuilder();
        String nextIndent = indent + delta;
        String nextNextIndent = nextIndent + delta;
        res.append("ProvidedSlot {\n");
        res.append(nextIndent).append("specification: ");
        if (null == specification) {
            res.append("null\n");
        } else {
            res.append(specification.deepToString(nextIndent, delta, maxDepth-1));
        }
        res.append(nextIndent).append("possibleParentAdapter: ");
        if (null == possibleParentAdapter) {
            res.append("null\n");
        } else {
            res.append(possibleParentAdapter.deepToString(nextIndent, delta, maxDepth-1));
        }
        res.append(nextIndent).append("possibleServiceProxy: ");
        res.append(possibleServiceProxy).append("\n");
        res.append(indent).append("} // ProvidedSlot\n");
        return res.toString();
    }

    public ProvidedSlot smartDeepCopy() {
        java.util.HashMap<Object,Object> conversion = new java.util.HashMap<Object,Object>();
        return smartDeepCopyInto(conversion);
    }
    /*package*/ ProvidedSlot smartDeepCopyInto(java.util.HashMap<Object,Object> conversion) {
        if (conversion.containsKey(this)) return (ProvidedSlot) conversion.get(this);
        ProvidedSlot ___res = new ProvidedSlot();
        conversion.put(this, ___res);
        if (null == specification) {
            ___res.specification = null;
        } else {
            ___res.specification = specification.smartDeepCopyInto(conversion);
        }
        if (null == possibleParentAdapter) {
            ___res.possibleParentAdapter = null;
        } else {
            ___res.possibleParentAdapter = possibleParentAdapter.smartDeepCopyInto(conversion);
        }
        ___res.possibleServiceProxy = possibleServiceProxy;
        return ___res;
    }
    /*package*/ ProvidedSlot() {
        this.specification = null;
        this.possibleParentAdapter = null;
        this.possibleServiceProxy = null;
    }

}
