// Autogenerated, edition is futile
package com.heeere.omiscidgui.eaa.adapterframework.model;

public class RequiredSlot {

    protected java.beans.PropertyChangeSupport ___pcs = new java.beans.PropertyChangeSupport(this);
    public void addPropertyChangeListener(java.beans.PropertyChangeListener l) {___pcs.addPropertyChangeListener(l);}
    public void removePropertyChangeListener(java.beans.PropertyChangeListener l) {___pcs.removePropertyChangeListener(l);}
    public RequiredSlot(ServiceSpecification specification, ProvidedSlot fullfilledBy) {
        this.specification = specification;
        this.fullfilledBy = fullfilledBy;
    }

    private ServiceSpecification specification;
    public ServiceSpecification getSpecification() {
        return specification;
    }
    public void setSpecification(ServiceSpecification specification) {
        ServiceSpecification __old = this.specification;
        this.specification = specification;
        ___pcs.firePropertyChange("specification", __old, this.specification);
    }

    private ProvidedSlot fullfilledBy;
    public ProvidedSlot getFullfilledBy() {
        return fullfilledBy;
    }
    public void setFullfilledBy(ProvidedSlot fullfilledBy) {
        ProvidedSlot __old = this.fullfilledBy;
        this.fullfilledBy = fullfilledBy;
        ___pcs.firePropertyChange("fullfilledBy", __old, this.fullfilledBy);
    }

    public String deepToString(String indent, String delta, int maxDepth) {
        if (maxDepth <= 0) { return "!!!MAX!!!\n";}
        StringBuilder res = new StringBuilder();
        String nextIndent = indent + delta;
        String nextNextIndent = nextIndent + delta;
        res.append("RequiredSlot {\n");
        res.append(nextIndent).append("specification: ");
        if (null == specification) {
            res.append("null\n");
        } else {
            res.append(specification.deepToString(nextIndent, delta, maxDepth-1));
        }
        res.append(nextIndent).append("fullfilledBy: ");
        if (null == fullfilledBy) {
            res.append("null\n");
        } else {
            res.append(fullfilledBy.deepToString(nextIndent, delta, maxDepth-1));
        }
        res.append(indent).append("} // RequiredSlot\n");
        return res.toString();
    }

    public RequiredSlot smartDeepCopy() {
        java.util.HashMap<Object,Object> conversion = new java.util.HashMap<Object,Object>();
        return smartDeepCopyInto(conversion);
    }
    /*package*/ RequiredSlot smartDeepCopyInto(java.util.HashMap<Object,Object> conversion) {
        if (conversion.containsKey(this)) return (RequiredSlot) conversion.get(this);
        RequiredSlot ___res = new RequiredSlot();
        conversion.put(this, ___res);
        if (null == specification) {
            ___res.specification = null;
        } else {
            ___res.specification = specification.smartDeepCopyInto(conversion);
        }
        if (null == fullfilledBy) {
            ___res.fullfilledBy = null;
        } else {
            ___res.fullfilledBy = fullfilledBy.smartDeepCopyInto(conversion);
        }
        return ___res;
    }
    /*package*/ RequiredSlot() {
        this.specification = null;
        this.fullfilledBy = null;
    }

}
