// Autogenerated, edition is futile
package com.heeere.omiscidgui.eaa.adapterframework.model;

public class ServiceProperty {

    protected java.beans.PropertyChangeSupport ___pcs = new java.beans.PropertyChangeSupport(this);
    public void addPropertyChangeListener(java.beans.PropertyChangeListener l) {___pcs.addPropertyChangeListener(l);}
    public void removePropertyChangeListener(java.beans.PropertyChangeListener l) {___pcs.removePropertyChangeListener(l);}
    public ServiceProperty(String name, String value) {
        this.name = name;
        this.value = value;
    }

    private String name;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        String __old = this.name;
        this.name = name;
        ___pcs.firePropertyChange("name", __old, this.name);
    }

    private String value;
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        String __old = this.value;
        this.value = value;
        ___pcs.firePropertyChange("value", __old, this.value);
    }

    public String deepToString(String indent, String delta, int maxDepth) {
        if (maxDepth <= 0) { return "!!!MAX!!!\n";}
        StringBuilder res = new StringBuilder();
        String nextIndent = indent + delta;
        String nextNextIndent = nextIndent + delta;
        res.append("ServiceProperty {\n");
        res.append(nextIndent).append("name: ");
        res.append(name).append("\n");
        res.append(nextIndent).append("value: ");
        res.append(value).append("\n");
        res.append(indent).append("} // ServiceProperty\n");
        return res.toString();
    }

    public ServiceProperty smartDeepCopy() {
        java.util.HashMap<Object,Object> conversion = new java.util.HashMap<Object,Object>();
        return smartDeepCopyInto(conversion);
    }
    /*package*/ ServiceProperty smartDeepCopyInto(java.util.HashMap<Object,Object> conversion) {
        if (conversion.containsKey(this)) return (ServiceProperty) conversion.get(this);
        ServiceProperty ___res = new ServiceProperty();
        conversion.put(this, ___res);
        ___res.name = name;
        ___res.value = value;
        return ___res;
    }
    /*package*/ ServiceProperty() {
        this.name = null;
        this.value = null;
    }

}
